spring.application.name=LifeManager
spring.datasource.generate-unique-name=false

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:mysql://localhost:3306/LifeManager
spring.datasource.username=root
spring.datasource.password=Alicja173!

coderslab.custom.property=my custom value
coderslab.course.name=Java Developer


server.error.include-stacktrace
server.error.include-message=always
server.error.include-binding-errors=always


springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.operationsSorter=method

